#!/bin/bash
echo "Deploying latest **PRODUCTION** Cliizii application to Zapier"
zapier login
zapier link
zapier test
zapier env 1.0.0 BASE_URL https://cliizii.chat
zapier env 1.0.0 BASE_API_URL https://cliizii.chat/api
zapier env 1.0.0 ACCOUNT_TEST_EMAIL zapiertest@mailinator.com
zapier env 1.0.0 ACCOUNT_TEST_PASS qwerty123
zapier push
